[env]
VENDOR_NAME = "Example GmbH"
VENDOR_URL = "https://localhost"
VENDOR_EMAIL = "example@example.com"

PRODUCT_NAME = "Freeverb"
PRODUCT_ID = "org.example.freeverb"

[alias]
# Building the xtask package in release mode is normally not necessary, but if
# you're going to compile other plugins in release mode then you'd need to
# recompile serde(-derive) because the xtask packages needs serde to parse the
# `bundler.toml` config file. To avoid needing to compile these expensive crates
# twice, we'll default to also running the xtask target in release mode.
xtask = "run --package xtask --release --"
xtask-debug = "run --package xtask --"

